version: '3'

volumes:
  db_data:
    name: ${VOLUME_ID}

services:

  db:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'BDD_FIREACADEMY'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'firefight'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'firefight'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

