version: '3'

services:

  db:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER} 
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} ls
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

