spring:
  application:
    name: DBH_ACADEMY  
  datasource:
    url: jdbc:h2:mem:bdd_ff;INIT=CREATE SCHEMA IF NOT EXISTS BDD_FIREFIGHT;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #change to validate in production mode
      use-new-id-generator-mappings: true #prevents HHH90000014: Found use of deprecated [org.hibernate.id.SequenceHiLoGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.

server:
  port: ${PORT:3000}   # HTTP (Tomcat) port
  
  
logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: WARN
    org.hibernate: INFO
    com.dbhacademy.firefight: DEBUG

  