spring:
  application:
    name: DBH_ACADEMY
  datasource:
    url: 'jdbc:h2:mem:BDD_FIREFIGHT;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS BDD_FIREFIGHT'
    username: 'sa'
    password: 
    initialization-mode: always
    platform: h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #change to validate in production mode
    show-sql: true
  thymeleaf:
    cache: false
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  devtools:
    livereload:
      enabled: true

server:
  port: ${PORT:3001}   # HTTP (Tomcat) port
  
logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: WARN
    org.hibernate: INFO
    com.dbhacademy.firefight: DEBUG
