
INSERT INTO BDD_FIREFIGHT.TB01_AGRUPACION VALUES (1,'CONOCIMIENTOS GENERALES'),
                                                 (2,'CONOCIMIENTOS ESPECIFICOS'),
                                                 (3,'TEMAS ESPECÍFICOS DEL SPEIS');
INSERT INTO BDD_FIREFIGHT.TB02_TEMA VALUES (1,'Constitución Española',1),
                                           (2,'Estatuto de Autonomía de la CV',1),
                                           (3,'Ley de Bases del Régimen Local',1),
                                           (4,'Ley de Régimen Local de la CV',1),
                                           (5,'Ley de Prevención de Riesgos Laborales',1),
                                           (6,'Estatuto Básico del Empleado Público',1),
                                           (7,'Ordenación y Gestión de la FPV',1),
                                           (8,'Ley de Incompatibilidades',1),
                                           (9,'Derecho Administrativo',1),
                                           (10,'Hacienda Pública y Administración Tributaria',1),
                                           (11,'Informática básica',1),
                                           (12,'Geografía de la Comunitat Valenciana',2),
                                           (13,'Organización y funcionamiento SPEIS',2),
                                           (14,'Ley SPEIS Comunitat Valenciana',2),
                                           (15,'Técnicas gráficas',2),
                                           (16,'Escalas y unidades de medida',2),
                                           (17,'Hidráulica',2),
                                           (18,'Comunicaciones',2),
                                           (19,'Vehículos de los Servicios de Bomberos',2),
                                           (20,'Equipamiento operativo',2),
                                           (21,'Equipos de Protección Individual (EPI)',2),
                                           (22,'Normas específicas en prevención de riesgos',2),
                                           (23,'Teoria del fuego',2),
                                           (24,'Mecanismos de extinción',2),
                                           (25,'Incendios de interior',2),
                                           (26,'Intervención en incendios urbanos',2),
                                           (27,'Incendios industriales',2),
                                           (28,'Incendios en túneles',2),
                                           (29,'Ventilación de incendios',2),
                                           (30,'Incendio forestal',2),
                                           (31,'Rescates en altura',2),
                                           (32,'Rescates en accidentes de tráfico',2),
                                           (33,'Otros rescates: ríos, riadas e inundaciones',2),
                                           (34,'Ascensores',2),
                                           (35,'Intervenciones sanitarias',2),
                                           (36,'Psicología de emergencias',2),
                                           (37,'Edificaciones e instalaciones',2),
                                           (38,'CTE - DBSI',2),
                                           (39,'Instalaciones de proteccion contra incendios',2),
                                           (40,'Patología y lesiones de la edificación',2),
                                           (41,'Riesgo eléctrico',2),
                                           (42,'Materias peligrosas',2),
                                           (43,'Riesgo radiológico',2),
                                           (44,'Instalaciones de gases combustibles',2),
                                           (45,'Conocimiento del término municipal',3),
                                           (46,'Organización y funcionamiento de los parques',3),
                                           (47,'Orden de vestuario',3),
                                           (48,'Incendio de vehículo en vía pública',3),
                                           (49,'Incendio contenedores y enseres en vía pública',3),
                                           (50,'Incendio forestal en la Devesa',3),
                                           (51,'Incendio industrial',3),
                                           (52,'Incendio en edificios de baja y media altura',3),
                                           (53,'Incendio en EGA',3),
                                           (54,'Incendio en Sótanos, Garajes y Bajos Comerciales',3),
                                           (55,'Accidente de tráfico',3),
                                           (56,'Salvamento en ascensores',3),
                                           (57,'Intervención con himenópteros',3),
                                           (58,'Comunicaciones Operativas',3),
                                           (59,'Samu',3),
                                           (60,'Plan Territorial de Emergencias',3),
                                           (61,'PAM frente al Riesgo de Inundaciones',3),
                                           (62,'PAM frente al Riesgo de Incendio Forestales',3),
                                           (63,'Plan de Igualdad',3);




INSERT INTO BDD_FIREFIGHT.TB05_EXAMEN VALUES 
(1,'Ayto. Valencia 2018 - Bombero'),
(2,'Cons. Valencia 2019 - Bombero'),
(3,'Ayto. Alicante 2020 - Oficial Específico'),
                                           (4,'Ayto. Alicante 2020 - Oficial Legislación'),
                                           (5,'Ayto. Alicante 2020 - Cabo'),
                                           (6,'Ayto. Alicante 2021 - Bombero Estabilización'),
                                           (7,'Ayto. Alicante 2021 - Bombero Libre'),
                                           (8,'Cons. Alicante 2021 - Cabo'),
                                           (9,'Cons. Alicante 2021 - Sargento'),
                                           (10,'Cons. Alicante 2021 - Suboficial'),
                                           (11,'Cons. Alicante 2021 - Bombero Libre'),
                                           (12,'Cons. Alicante 2021 - Bombero Estabilización');

INSERT INTO BDD_FIREFIGHT.TB03_PREGUNTA(id,texto,tema_id,examen_id) VALUES (1,'¿Qué Artículo de la Constitución está dedicado a la irretroactividad de las disposiciones  desfavorables o restrictivas de derechos individuales?',1,NULL),
(2,'Según el Artículo 1.2 de la Constitución Española, ¿De dónde emanan los poderes del Estado?',1,NULL),
(3,'¿Cómo se denomina el Título Preliminar de la C.E?',1,NULL),
(4,'¿Por qué no están constituidas las fuerzas armadas?',1,NULL),
(5,'Las bases de la organización militar se regulará conforme a los principios previstos en:',1,NULL),
(6,'Según la Constitución Española de 1978, las banderas y enseñas propias de las Comunidades Autónomas: (Comunidad de Madrid, 2014)',1,NULL),
(7,'La solidaridad entre las autonomías de las nacionalidades  y  regiones  que integran  la  nación española es  un derecho  que:',1,NULL),
(8,'Según el Artículo 1 de la Constitución Española,  la  forma  política del  Estado  español es: (Comunidad  de Madrid,  2014)',1,NULL),
(9,'Según la Constitución;  ¿Que  se  fundamenta en  la  indisoluble unidad de  la nación  española?',1,NULL),
(10,'¿Quién está sujeto a la Constitución y al resto del ordenamiento jurídico?',1,NULL),
(11,'Sólo uno de los siguientes principios está garantizado constitucionalmente:',1,NULL),
(12,'¿Qué Artículo de la CE contempla los valores superiores del ordenamiento jurídico?',1,NULL),
(13,'La integridad territorial de España y  su  ordenamiento  constitucional es  una  misión que las  fuerzas armadas  deben:',1,NULL),
(14,'Según la actual Constitución Española, y conforme a sus principios, las  bases  de  la organización  militar  serán reguladas. (Comunidad  de Madrid,  2011)',1,NULL),
(15,'La soberanía e  independencia  de  España es  una  misión que las  fuerzas armadas  deben:',1,NULL),
(16,'La Constitución Española de 1978 garantiza que las disposiciones sancionadoras no favorables o restrictivas de derechos individuales sean: (Comunidad de Madrid, 2011)',1,NULL),
(17,'Según la Constitución Española, el ordenamiento constitucional es una misión que las fuerzas armadas deben:',1,NULL),
(18,'Los principios establecidos en el Artículo 9.3:',1,NULL),
(19,'Según la CE la soberanía nacional reside en:',1,NULL),
(20,'\"Corresponde a los poderes públicos promover las condiciones para que la libertad y la igualdad del individuo y de los grupos en que se integran sean reales y efectivas; remover los obstáculos que impidan o dificulten su plenitud y facilitar la participación de todos los ciudadanos en la  vida  política,  económica, cultural  y  social.\" Este enunciado  se encuentra  en:',1,NULL),
(21,'¿Cuál es el instrumento fundamental para la participación política?',1,NULL),
(22,'¿A quién reconoce y garantiza la Constitución Española  de  1978  el derecho  a  la autonomía? (Comunidad  de Madrid,  2011)',1,NULL),
(23,'¿Qué lengua es oficial en todo el territorio español?',1,NULL),
(24,'El derecho de autonomía está reconocido, dentro de la Constitución Española en:',1,NULL),
(25,'De acuerdo con el Artículo 9.3 de la CE se garantiza (indica la falsa):',1,NULL),
(26,'Según el Articulo 2 de la Constitución Española. ¿En que se fundamenta la Constitución?',1,NULL),
(27,'Según la Constitución Española, indica la falsa:',1,NULL),
(28,'La forma política del Estado Español en la Constitución Española es: (Comunidad de Madrid, 2011)',1,NULL),
(29,'¿Cuál de los siguientes principios no está reconocido en la Constitución?',1,NULL),
(30,'Los poderes del Estado: Señala la correcta según la Constitución Española (Comunidad  de Madrid,  2014)',1,NULL),
(31,'España se constituye en un Estado social y democrático de Derecho, que  propugna  como  valores superiores  de  su ordenamiento jurídico:  (indica la  falsa)',1,NULL),
(32,'¿A quién corresponde, según la CE, promover las condiciones para que la libertad y la igualdad de todos los españoles sean reales y efectivas?',1,NULL),
(33,'Para que Ceuta y Melilla puedan tener un Estatuto de Autonomía: (Comunidad de Madrid, 2014)',1,NULL),
(34,'¿Cuál es la entidad local con  personalidad  jurídica  propia, según  la  Constitución Española? (Comunidad  de Madrid,  2011)',1,NULL),
(35,'Los Municipios forman parte:',1,NULL),
(36,'Las  relaciones  entre  comunidades, para  celebrar  acuerdos y convenios,  viene regulado  en:',1,NULL),
(37,'En la Constitución de 1978, la provincia:',1,NULL),
(38,'El  Capítulo  III,  del Título  VIII  de la C.E.  contiene los  Artículos:',1,NULL),
(39,'\"Ninguna autoridad podrá adoptar medidas que directa o indirectamente obstaculicen la libertad de circulación y establecimiento de las personas y la libre circulación de bienes en todo el territorio español\". Este enunciado viene en:',1,NULL),
(40,'Las Comunidades Autónomas vienen reguladas  en  el  Titulo VIII  de  la Constitución pero  ¿En qué Capitulo?',1,NULL),
(41,'Denominación del Capítulo II, del Título VIII de la Constitución Española',1,NULL),
(42,'Las haciendas locales, según la Constitución Española, se nutrirán fundamentalmente de:',1,NULL),
(43,'\"El Estado garantiza la realización efectiva del principio de solidaridad consagrado en el Artículo 2 de la Constitución, velando por  el  establecimiento  de un  equilibrio  económico\" Este enunciado  viene definido  en:',1,NULL),
(44,'Nuestro sistema tributario debe ser:',1,NULL),
(45,'¿Cuál de las siguientes entidades no compone la Administración Local, según el Capítulo II del Título VIII de la C.E.?',1,NULL),
(46,'Respecto al Artículo 141 de la C.E. indica la falsa:',1,NULL),
(47,'Las Diputaciones Provinciales: (Comunidad de Madrid, 2014)',1,NULL),
(48,'Según el Artículo 140 de la Constitución Española, señala en enunciado correcto:',1,NULL),
(49,'Según la Constitución Española, señala la frase incorrecta:',1,NULL),
(50,'Según la Constitución Española, corresponde a los poderes públicos:',1,NULL),
(51,'Según la Constitución Española, señala la frase incorrecta:',1,NULL),
(52,'Según la Constitución Española, ¿Qué regulara la Ley respecto del Concejo Abierto?',1,NULL),
(53,'Según la Constitución Española, la iniciativa del proceso autonómico por el Artículo 143, corresponde a todas las Diputaciones interesadas o al órgano interinsular correspondiente y a las dos terceras partes de los Municipios cuya población represente, al menos, la mayoría del censo electoral de cada provincia o isla. Estos requisitos deberán ser cumplidos en el plazo de seis meses:',1,NULL),
(54,'Según la Constitución Española, las Comunidades Autónomas podrán actuar como delegados o colaboradores del Estado para:',1,NULL),
(55,'Según la Constitución Española, las Comunidades Autónomas podrán asumir competencias en:',1,NULL),
(56,'Según la Constitución Española, señala la frase correcta:',1,NULL),
(57,'La Constitución Española prevé en su Artículo octavo que, las Fuerzas Armadas, tienen como misión garantizar la:',1,NULL),
(58,'Según la Constitución Española, señala la afirmación correcta:',1,NULL),
(59,'Según la Constitución Española, ¿Quienes deberán promover las condiciones para que la libertad y la igualdad del individuo y de los grupos en que se integra sean reales y efectivas;  remover los obstáculos que impidan o dificulten su plenitud y facilitar la participación de todos los ciudadanos en la vida política, económica, cultural y social.?',1,NULL),
(60,'Según establece la Constitución, el Ejercito de Tierra, la Armada y el Ejército del Aire constituyen:',1,NULL),
(61,'Según el art. 5 de la CE, la villa de Madrid es la:',1,NULL),
(62,'Según la Constitución Española, señala la correcta:',1,NULL),
(63,'La ampliación de competencias de las Comunidades Autónomas, según el Artículo 148.2 de la Constitución Española, requerirá:',1,NULL),
(64,'Las diferencias entre los Estatutos de las distintas Comunidades Autónomas ¿Qué  no podrán implicar, en ningún caso?',1,NULL),
(65,'El gobierno y la administración autónoma de las provincias estarán encomendados, según la CE:',1,NULL),
(66,'Según la Constitución Española, ¿Que se considerará por el Estado, según el Artículo 149,  como deber y atribución esencial?',1,NULL),
(67,'Según la Constitución Española, si la iniciativa autonómica se frustrase, la misma podría ser reiniciada transcurrido un plazo que será:',1,NULL),
(68,'Según la Constitución Española, el Artículo 140 garantiza:',1,NULL),
(69,'Según el Artículo 148 de la Constitución Española, las Comunidades Autónomas podrán asumir competencias en una serie de materias. Indique si puede asumir competencias en materia de obras públicas y, en caso afirmativo, en qué términos:',1,NULL),
(70,'De acuerdo con el Artículo 140 de la Constitución Española, la potestad legislativa de los Municipios corresponde a:',1,NULL),
(71,'Según la Constitución Española, las Leyes Marco:',1,NULL),
(72,'Según el Artículo 1, apartado 1, de la Constitución Española de 1978:',1,NULL),
(73,'Según el Artículo 3, apartado 1, de la Constitución Española de 1978:',1,NULL),
(74,'Según el Artículo 6 de la Constitución Española de 1978:',1,NULL),
(75,'Uno de los siguientes principios no está garantizado por la Constitución Española de 1978:',1,NULL),
(76,'Según la Constitución Española, el nombramiento de los presidentes de las Comunidades Autónomas corresponde:',1,NULL),
(77,'Según el Artículo 9 de la Constitución, ¿a qué están sujetos los poderes públicos y los ciudadanos?',1,NULL),
(78,'Una de las siguientes materias no es regulada en el Título Preliminar de la Constitución Española:',1,NULL),
(79,'La Constitución se fundamenta:',1,NULL),
(80,'Las Comunidades Autónomas pueden:',1,NULL),
(81,'La Constitución Española actualmente vigente rige en España desde:',1,NULL),
(82,'La CE garantiza a las distintas entidades territoriales en que se organiza el Estado:',1,NULL),
(83,'La Constitución Española establece el principio de autonomía de los Municipios en su Artículo:',1,NULL),
(84,'La igualdad de los españoles en sus derechos y obligaciones independientemente del territorio en que residan se recoge en:',1,NULL),
(85,'La CE es una Constitución:',1,NULL),
(86,'El Estado no se organiza territorialmente en:',1,NULL),
(87,'De acuerdo con la Constitución de 1978, con respecto a los partidos políticos, su creación y el ejercicio de su actividad serán:',1,NULL),
(88,'La votación sobre la cuestión de confianza:',1,NULL),
(89,'Según el art. 147 de la Constitución Española de 1978, los Estatutos de Autonomía:',1,NULL),
(90,'¿La Constitución Española de 1978 ha sufrido alguna reforma?',1,NULL),
(91,'Según el art. 138.1 de la Constitución Española de 1978, el Estado garantiza:',1,NULL),
(92,'De acuerdo con el artículo 1 de la Constitución Española, ¿Cuál es la forma política del Estado español?',1,NULL),
(93,'La Constitución Española en su artículo 2, establece:',1,NULL),
(94,'El art 141 de la Constitución Española define la provincia como:',1,NULL),
(95,'De acuerdo con el artículo 142 de la Constitución Española, las Haciendas Locales se nutrirán de:',1,NULL),
(96,'De acuerdo con el artículo 141.4 de la Constitución Española, en los archipiélagos, las islas tendrán además su administración propia en forma de:',1,NULL),
(97,'Las bases de la organización militar, conforme a los principios constitucionales:',1,NULL),
(98,'¿Sobre qué materia tiene el Estado competencia exclusiva?',1,NULL),
(99,'Según el artículo 141 de la Constitución Española de 1978, cualquier alteración de los límites provinciales habrá de ser aprobada por las Cortes Generales mediante:',1,NULL),
(100,'El artículo 9 de la Constitución Española garantiza:',1,NULL);

INSERT INTO BDD_FIREFIGHT.tb04_respuesta VALUES (1,FALSE,'Artículo 9.2',1),
(2,TRUE,'Artículo 9.3',1),
(3,FALSE,'Artículo 9.4',1),
(4,FALSE,'Artículo 10',1),
(5,FALSE,'De la soberanía española',2),
(6,FALSE,'De los poderes Públicos',2),
(7,FALSE,'De la monarquía parlamentaria',2),
(8,TRUE,'Del Pueblo Español',2),
(9,FALSE,'De los principios básicos',3),
(10,FALSE,'De los principios generales',3),
(11,FALSE,'Preámbulo',3),
(12,TRUE,'Ninguna es correcta',3),
(13,FALSE,'La armada',4),
(14,FALSE,'Ejercito de aire',4),
(15,FALSE,'Ejército de tierra',4),
(16,TRUE,'Ejercito de mar',4),
(17,FALSE,'La Ley',5),
(18,FALSE,'Una Ley Ordinaria',5),
(19,FALSE,'Una Ley Orgánica',5),
(20,TRUE,'La Constitución',5),
(21,FALSE,'Representan un patrimonio cultural que será objeto de especial respeto y protección',6),
(22,TRUE,'Podrán reconocerse en los estatutos',6),
(23,FALSE,'Podrán reconocerse por los órganos autonómicos',6),
(24,FALSE,'Deberán reconocerse en los respectivos estatutos',6),
(25,FALSE,'Se protege',7),
(26,FALSE,'Se garantiza',7),
(27,TRUE,'Se reconoce y se garantiza',7),
(28,FALSE,'Se reconoce',7),
(29,FALSE,'La Democracia parlamentaria',8),
(30,TRUE,'La Monarquía parlamentaria',8),
(31,FALSE,'La Monarquía constitucional',8),
(32,FALSE,'La Monarquía democrática',8),
(33,FALSE,'España',9),
(34,TRUE,'La Constitución',9),
(35,FALSE,'El Estado',9),
(36,FALSE,'El Estado español',9),
(37,FALSE,'Los ciudadanos y la administración',10),
(38,TRUE,'Los ciudadanos y los poderes públicos',10),
(39,FALSE,'Las personas y la administración',10),
(40,FALSE,'Los españoles y los poderes públicos',10),
(41,TRUE,'La responsabilidad e interdicción de la arbitrariedad de los poderes públicos',11),
(42,FALSE,'La responsabilidad e interdicción de la arbitrariedad de la Administración Pública, tanto nacional, como autonómica o local',11),
(43,FALSE,'La responsabilidad de la Administración Pública',11),
(44,FALSE,'La interdicción de la arbitrariedad del poder judicial',11),
(45,FALSE,'Artículo 9.1',12),
(46,FALSE,'Artículo 10',12),
(47,FALSE,'Artículo 9.3',12),
(48,TRUE,'Artículo 1.1',12),
(49,FALSE,'Garantizar y asegurar',13),
(50,TRUE,'Defender',13),
(51,FALSE,'Asegurar',13),
(52,FALSE,'Garantizar',13),
(53,TRUE,'Mediante Ley Orgánica',14),
(54,FALSE,'Mediante Ley de Bases',14),
(55,FALSE,'Mediante Estatuto Básico',14),
(56,FALSE,'Mediante Ley Ordinaria',14),
(57,FALSE,'Defender y asegurar',15),
(58,FALSE,'Defender',15),
(59,FALSE,'Garantizar y defender',15),
(60,TRUE,'Garantizar',15),
(61,FALSE,'Nulas de Pleno derecho',16),
(62,FALSE,'Anulables',16),
(63,TRUE,'Irretroactivas',16),
(64,FALSE,'Retroactivas',16),
(65,TRUE,'Defender',17),
(66,FALSE,'Garantizar',17),
(67,FALSE,'Asegurar',17),
(68,FALSE,'Proteger',17),
(69,FALSE,'Se garantizan y reconocen',18),
(70,TRUE,'Se garantizan',18),
(71,FALSE,'Se reconocen',18),
(72,FALSE,'Se reconocer y se aseguran',18),
(73,FALSE,'El Gobierno',19),
(74,FALSE,'El jefe de Estado',19),
(75,FALSE,'Las Cortes Generales',19),
(76,TRUE,'El pueblo español',19),
(77,TRUE,'Artículo 9',20),
(78,FALSE,'Artículo 10',20),
(79,FALSE,'Artículo 14',20),
(80,FALSE,'Articulo 28',20),
(81,FALSE,'Las asociaciones de empresarios',21),
(82,FALSE,'Todos son instrumentos fundamentales para la participación política',21),
(83,FALSE,'Los sindicatos de trabajadores',21),
(84,TRUE,'Los partidos políticos',21),
(85,FALSE,'A las Comunidades Autónomas',22),
(86,FALSE,'A las provincias y regiones',22),
(87,TRUE,'A las nacionalidades y regiones',22),
(88,FALSE,'A las Comunidades y Ciudades Autónomas',22),
(89,FALSE,'El español',23),
(90,FALSE,'El castellano y las restantes lenguas oficiales de cada Comunidad Autónoma',23),
(91,FALSE,'El español y las restantes lenguas oficiales de cada Comunidad Autónoma',23),
(92,TRUE,'El castellano',23),
(93,FALSE,'Artículo 147',24),
(94,FALSE,'Artículo 143',24),
(95,FALSE,'Articulo 142',24),
(96,TRUE,'Artículo 2',24),
(97,TRUE,'El principio de irretroactividad de las disposiciones sancionadoras',25),
(98,FALSE,'El principio de responsabilidad',25),
(99,FALSE,'El principio de seguridad jurídica',25),
(100,FALSE,'El principio de jerarquía normativa',25),
(101,TRUE,'En la indisoluble unidad de la Nación española',26),
(102,FALSE,'En las nacionalidades y regiones que la integran',26),
(103,FALSE,'En la patria común e indivisible de todos los españoles',26),
(104,FALSE,'En el pueblo español',26),
(105,FALSE,'Todos los españoles tienen el deber de conocer el Castellano, que es la lengua española oficial del Estado, y tienen el derecho a usarla',27),
(106,FALSE,'Las Comunidades autónomas utilizarán sus banderas y enseñas propias en los edificios públicos y actos oficiales',27),
(107,FALSE,'La bandera de España está formada por 3 franjas horizontales, dispuestas en el orden rojo, amarillo y rojo, siendo la franja amarilla de doble anchura que cada una de las rojas',27),
(108,TRUE,'Todas las respuestas son correctas',27),
(109,FALSE,'La Corona inviolable y hereditaria',28),
(110,FALSE,'Un Parlamento refrendado por la Corona',28),
(111,TRUE,'Una Monarquía Parlamentaria',28),
(112,FALSE,'Un Gobierno democrático, expresión de la mayoría parlamentaria',28),
(113,FALSE,'Responsabilidad de los poderes públicos',29),
(114,TRUE,'Retroactividad de las disposiciones sancionadoras',29),
(115,FALSE,'Publicidad de las normas',29),
(116,FALSE,'Jerarquía normativa',29),
(117,FALSE,'Cimentan la soberanía nacional',30),
(118,FALSE,'Son tres: ejecutivo, legislativo y judicial',30),
(119,TRUE,'Emanan del pueblo',30),
(120,FALSE,'Cimentan la indisoluble unidad de la nación española',30),
(121,FALSE,'La igualdad',31),
(122,FALSE,'La justicia',31),
(123,FALSE,'La libertad',31),
(124,TRUE,'Ninguna de las respuestas anteriores es falsa',31),
(125,TRUE,'Poderes públicos',32),
(126,FALSE,'Nación',32),
(127,FALSE,'Estado',32),
(128,FALSE,'Gobierno de la nación',32),
(129,FALSE,'No es posible según la Constitución, deben integrarse en la Comunidad de Andalucía',33),
(130,FALSE,'Es preciso un referéndum entre sus habitantes y los de Andalucía',33),
(131,FALSE,'Es preciso un referéndum entre sus habitantes mayores de edad',33),
(132,TRUE,'Lo pueden autorizar las Cortes mediante Ley orgánica',33),
(133,TRUE,'La Provincia',34),
(134,FALSE,'El Municipio',34),
(135,FALSE,'Los territorios insulares',34),
(136,FALSE,'La Comunidad Autónoma',34),
(137,FALSE,'De la Administración periférica del Estado',35),
(138,FALSE,'De la Administración autonómica',35),
(139,FALSE,'De la Administración Central',35),
(140,TRUE,'De la Administración Local',35),
(141,TRUE,'Artículo 145 de la C.E',36),
(142,FALSE,'Artículo 143 de la C.E',36),
(143,FALSE,'Artículo 142 de la C.E',36),
(144,FALSE,'Artículo 144 de la C.E',36),
(145,FALSE,'Puede ser suprimida por Ley autonómica',37),
(146,FALSE,'No aparece citada',37),
(147,TRUE,'Es una división territorial para el cumplimiento de las actividades del Estado',37),
(148,FALSE,'Es una entidad local sin personalidad jurídica propia, determinada por la agrupación de municipios',37),
(149,FALSE,'Del 142 al 147',38),
(150,TRUE,'Del 143 al 158',38),
(151,FALSE,'Del 141 al 151',38),
(152,FALSE,'Del 142 al 148',38),
(153,FALSE,'Articulo 17',39),
(154,TRUE,'Articulo 139',39),
(155,FALSE,'Articulo 18',39),
(156,FALSE,'Articulo 20',39),
(157,FALSE,'II',40),
(158,FALSE,'I',40),
(159,TRUE,'III',40),
(160,FALSE,'IV',40),
(161,FALSE,'De los municipios',41),
(162,FALSE,'Del municipio',41),
(163,TRUE,'De la Administración local',41),
(164,FALSE,'De la provincia',41),
(165,TRUE,'Tributos propios y de la participación en los del Estado y de las Comunidades Autónomas',42),
(166,FALSE,'De recursos de derecho público, privado y de participación en los del Estado y las Comunidades Autónomas',42),
(167,FALSE,'Tributos propios',42),
(168,FALSE,'Recursos propios',42),
(169,FALSE,'Articulo 143',43),
(170,FALSE,'Articulo 146',43),
(171,FALSE,'Articulo 137',43),
(172,TRUE,'Articulo 138',43),
(173,TRUE,'Justo',44),
(174,FALSE,'Equitativo',44),
(175,FALSE,'Social',44),
(176,FALSE,'Democrático',44),
(177,FALSE,'Municipios',45),
(178,FALSE,'Provincias',45),
(179,TRUE,'Comunidades autónomas',45),
(180,FALSE,'Todas son correctas',45),
(181,FALSE,'La provincia es una entidad local con personalidad jurídica propia',46),
(182,TRUE,'Las agrupaciones de municipios diferentes de la provincia habrán de ser aprobada por las Cortes Generales mediante Ley orgánica',46),
(183,FALSE,'El gobierno y la administración autónoma de las provincias estarán encomendados a Diputaciones u otras Corporaciones de carácter representativo',46),
(184,FALSE,'En los archipiélagos, las islas tendrán además su administración propia en forma de Cabildos o Consejos',46),
(185,FALSE,'Forman parte de la Administración periférica del Estado',47),
(186,TRUE,'Forman parte de la Administración Local',47),
(187,FALSE,'Forman parte de la Administración autonómica',47),
(188,FALSE,'Forman parte de la Administración Central',47),
(189,FALSE,'Los municipios gozarán de personalidad jurídica propia',48),
(190,FALSE,'Los Concejales serán elegidos por los Alcaldes o por los vecinos',48),
(191,FALSE,'Dos son correctas',48),
(192,TRUE,'Los municipios gozarán de personalidad jurídica plena',48),
(193,FALSE,'El castellano es la lengua española oficial del Estado',49),
(194,FALSE,'Todos los españoles tienen el deber de conocerla y el derecho a usarla',49),
(195,TRUE,'Las demás lenguas españolas serán también oficiales en las respectivas Comunidades Autónomas de acuerdo con la Constitución y sus Estatutos',49),
(196,FALSE,'La riqueza de las distintas modalidades lingüísticas de España es un patrimonio cultural que será objeto de especial respeto y protección',49),
(197,FALSE,'a) Remover las condiciones para que la libertad y la igualdad del individuo y de los grupos en que se integra sean reales y efectivas',50),
(198,FALSE,'b) Promover los obstáculos que impidan o dificulten su plenitud y facilitar la participación de todos los ciudadanos en la vida política, económica, cultural y social',50),
(199,FALSE,'c) A y B son correctas',50),
(200,TRUE,'d) Ninguna es correcta',50),
(201,FALSE,'El Estado garantiza la realización efectiva del principio de solidaridad, consagrado en el Artículo 2 de la Constitución',51),
(202,TRUE,'Velando por el establecimiento de un equilibrio económico, adecuado y justo, entre las diversas partes del territorio español, y atendiendo en particular a las circunstancias de las zonas de montaña',51),
(203,FALSE,'Las diferencias entre los Estatutos de las distintas Comunidades Autónomas no podrán implicar, en ningún caso, privilegios económicos o sociales',51),
(204,FALSE,'Todos los españoles tienen los mismos derechos y obligaciones en cualquier parte de territorio del Estado',51),
(205,FALSE,'Su régimen',52),
(206,TRUE,'Las condiciones en las que proceda',52),
(207,FALSE,'Su establecimiento',52),
(208,FALSE,'Ninguna es correcta',52),
(209,FALSE,'Desde el primer acuerdo adoptado al respecto por alguna de los ayuntamientos interesados',53),
(210,TRUE,'Desde el primer acuerdo adoptado al respecto por alguna de las Corporaciones locales interesadas',53),
(211,FALSE,'Desde el primer acuerdo adoptado al respecto por cualquiera de los interesados',53),
(212,FALSE,'Ninguna es correcta',53),
(213,TRUE,'La recaudación, la gestión y la liquidación de los recursos tributarios de aquél, de acuerdo con las Leyes y los Estatutos',54),
(214,FALSE,'La gestión y la liquidación de los recursos tributarios de aquél, de acuerdo con las Leyes y los Estatutos',54),
(215,FALSE,'La recaudación, la gestión y la liquidación de los impuestos de aquél, de acuerdo con las Leyes y los Estatutos',54),
(216,FALSE,'La gestión y la liquidación de los impuestos de aquél, de acuerdo con las Leyes y los Estatutos',54),
(217,TRUE,'La gestión en materia de protección del medio ambiente',55),
(218,FALSE,'Hacienda general y Deuda del Estado',55),
(219,FALSE,'Administración de Justicia',55),
(220,FALSE,'Pesca marítima',55),
(221,FALSE,'La riqueza de las distintas modalidades lingüísticas de España es un patrimonio cultural que será objeto de especial protección',56),
(222,FALSE,'La soberanía nacional reside en el pueblo, del que emanan los poderes del Estado',56),
(223,FALSE,'Las Leyes podrán reconocer banderas y enseñas propias de las Comunidades Autónomas',56),
(224,TRUE,'Los ciudadanos y los poderes públicos están sujetos a la Constitución y al resto del ordenamiento jurídico',56),
(225,FALSE,'Soberanía y dependencia de España ',57),
(226,FALSE,'Independencia y autonomía de España  ',57),
(227,TRUE,'Soberanía e independencia de España  ',57),
(228,FALSE,'Ninguna es correcta ',57),
(229,FALSE,'Los sindicatos de trabajadores y las asociaciones empresariales contribuyen a la defensa y promoción de los intereses económicos y sociales que les son propios',58),
(230,FALSE,'La estructura interna y funcionamiento de los partidos políticos, sindicatos de trabajadores y asociaciones empresariales, deberán ser democráticos',58),
(231,FALSE,'Los estatutos podrán reconocer banderas y enseñas propias de las Comunidades Autónomas. Estas se utilizarán junto a la bandera de España en sus edificios públicos y en sus actos oficiales',58),
(232,TRUE,'Todas son correctas',58),
(233,FALSE,'Los partidos politos',59),
(234,FALSE,'Los poderes del estado',59),
(235,TRUE,'Los poderes públicos',59),
(236,FALSE,'La Administración del Estado',59),
(237,FALSE,'El ejército Español',60),
(238,FALSE,'La soberanía Española',60),
(239,TRUE,'Las Fuerzas Armadas',60),
(240,FALSE,'Ninguna es correcta',60),
(241,FALSE,'Capital de España',61),
(242,FALSE,'Capital del Estado Español',61),
(243,TRUE,'Capital del Estado',61),
(244,FALSE,'Ninguna es correcta',61),
(245,FALSE,'El Estado, en materias de competencia estatal, podrán atribuir a todas o a alguna de las Comunidades Autónomas la facultad de dictar, para sí mismas, normas legislativas en el marco de los principios, bases y directrices fijados por la Ley estatal',62),
(246,FALSE,'El Gobierno, en materias de competencia estatal, podrán atribuir a todas o a alguna de las Comunidades Autónomas la facultad de dictar, para sí mismas, normas legislativas en el marco de los principios, bases y directrices fijados por la Ley estatal',62),
(247,FALSE,'El Congreso, en materias de competencia estatal, podrán atribuir a todas o a alguna de las Comunidades Autónomas la facultad de dictar, para sí mismas, normas legislativas en el marco de los principios, bases y directrices fijados por la Ley estatal',62),
(248,TRUE,'Las Cortes Generales, en materias de competencia estatal, podrán atribuir a todas o a alguna de las Comunidades Autónomas la facultad de dictar, para sí mismas, normas legislativas en el marco de los principios, bases y directrices fijados por la Ley estatal',62),
(249,FALSE,'Que esta ampliación se realice en el marco establecido por el Artículo 149',63),
(250,FALSE,'Que hayan transcurrido cinco años',63),
(251,FALSE,'Que se reforme el Estatuto de Autonomía',63),
(252,TRUE,'Todas son correctas',63),
(253,TRUE,'a) Privilegios económicos o sociales',64),
(254,FALSE,'b) Medidas que directa o indirectamente obstaculicen la libertad de circulación y establecimiento de las personas y la libre circulación de bienes en todo el territorio español',64),
(255,FALSE,'c) A y B son correctas ',64),
(256,FALSE,'d) Ninguna es correcta',64),
(257,FALSE,'A Diputaciones u otras Corporaciones de carácter electivo',65),
(258,TRUE,'A Diputaciones u otras Corporaciones de carácter representativo',65),
(259,FALSE,'A Diputaciones, Cabildos o Consejos en las islas',65),
(260,FALSE,'Ninguna es correcta',65),
(261,FALSE,'La defensa del patrimonio artístico',66),
(262,TRUE,'El servicio de la cultura',66),
(263,FALSE,'La enseñanza',66),
(264,FALSE,'La coordinación educativa',66),
(265,FALSE,'Como mínimo de seis meses',67),
(266,FALSE,'Como máximo de seis meses',67),
(267,TRUE,'Como mínimo de cinco años',67),
(268,FALSE,'Como máximo de cinco años',67),
(269,FALSE,'La autonomía de los municipios, que gozarán de personalidad jurídica propia',68),
(270,FALSE,'La autonomía de los municipios, que gozarán de personalidad jurídica delegada',68),
(271,FALSE,'La autonomía de las Provincias y municipios, que gozarán de personalidad jurídica propia',68),
(272,TRUE,'La autonomía de los municipios, que gozarán de personalidad jurídica plena',68),
(273,FALSE,'No, cuando se trata de obras públicas de interés general',69),
(274,FALSE,'Sí, en los términos que se establezcan en la Ley orgánica por la que asuman dicha competencia',69),
(275,TRUE,'Sí, cuando se trate de obras públicas de interés de la Comunidad Autónoma dentro de su propio territorio',69),
(276,FALSE,'Sí, en todo caso, salvo aquellas obras de titularidad estatal',69),
(277,FALSE,'Sus respectivos Ayuntamientos',70),
(278,FALSE,'El Pleno',70),
(279,FALSE,'Los vecinos del municipio mediante consulta vecinal',70),
(280,TRUE,'Ninguna es correcta',70),
(281,FALSE,'Son normas legislativas fijadas por el Gobierno',71),
(282,TRUE,'Son normas legislativas fijadas por una Ley Estatal',71),
(283,FALSE,'Son normas legislativas fijadas por las Comunidades Autónomas',71),
(284,FALSE,'Son normas legislativas fijadas por las Comunidades Autónomas así como las Corporaciones Locales',71),
(285,FALSE,'España se constituye en un Estado social y democrático de Derecho, que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad, la fraternidad y el pluralismo político',72),
(286,TRUE,'España se constituye en un Estado social y democrático de Derecho, que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político',72),
(287,FALSE,'España se constituye en un Estado liberal y democrático de Derecho, que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político',72),
(288,FALSE,'España se constituye en un Estado de Monarquía Parlamentaria, que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político',72),
(289,FALSE,'El castellano y todas las lenguas oficiales de las respectivas Comunidades Autónomas, son las lenguas oficiales del Estado. Todos los españoles tienen el deber de conocerlas y el derecho a usarlas',73),
(290,FALSE,'El castellano y todas las lenguas oficiales de las respectivas Comunidades Autónomas, son las lenguas oficiales del Estado. Todos los españoles tienen el derecho a usarlas',73),
(291,TRUE,'El castellano es la lengua española oficial del Estado. Todos los españoles tienen el deber de conocerla y el derecho a usarla',73),
(292,FALSE,'Ninguna de las respuestas es correcta',73),
(293,TRUE,'La estructura interna y el funcionamiento de los partidos políticos deberán ser democráticos',74),
(294,FALSE,'La composición y el funcionamiento de los partidos políticos deberán ser democráticos',74),
(295,FALSE,'Las reglas de afiliación y los procedimientos para la adopción de acuerdos de los partidos políticos deberán ser democráticos',74),
(296,FALSE,'Ninguna de las respuestas es correcta',74),
(297,FALSE,'El de jerarquía normativa',75),
(298,TRUE,'El de irretroactividad de las disposiciones sancionadoras favorables',75),
(299,FALSE,'El de la publicidad de las normas',75),
(300,FALSE,'El de legalidad',75),
(301,TRUE,'Al Rey',76),
(302,FALSE,'A las Asambleas Legislativas de las Comunidades Autónomas',76),
(303,FALSE,'Al Presidente del Gobierno',76),
(304,FALSE,'A las Cortes Generales',76),
(305,FALSE,'A la Constitución y a la Ley',77),
(306,FALSE,'A la Ley y al ordenamiento jurídico',77),
(307,FALSE,'A la Constitución y al resto del ordenamiento jurídico',77),
(308,TRUE,'A la Constitución, a la Ley y al resto del ordenamiento jurídico',77),
(309,TRUE,'Las Cortes Generales',78),
(310,FALSE,'Las Asociaciones de Empresarios',78),
(311,FALSE,'Las Fuerzas Armadas',78),
(312,FALSE,'Los Partidos Políticos',78),
(313,FALSE,'En la unidad de la Nación Española',79),
(314,FALSE,'En el compromiso de unidad de todos los pueblos y nacionalidades integrantes de la Nación Española',79),
(315,TRUE,'En la indisoluble unidad de la Nación Española',79),
(316,FALSE,'En la pluralidad de pueblos integrantes de la Nación Española',79),
(317,FALSE,'a) Celebrar convenios entre sí',80),
(318,FALSE,'b) Federarse',80),
(319,FALSE,'c) Establecer acuerdos de cooperación, con autorización de las Cortes Generales',80),
(320,TRUE,'d) A y C son correctas',80),
(321,FALSE,'El 27 de diciembre de 1978',81),
(322,TRUE,'El 29 de diciembre de 1978',81),
(323,FALSE,'El 6 de diciembre de 1978',81),
(324,FALSE,'El 28 de diciembre de 1978',81),
(325,FALSE,'Armonía',82),
(326,FALSE,'Independencia y solidaridad',82),
(327,FALSE,'Autonomía',82),
(328,TRUE,'Autonomía y solidaridad',82),
(329,FALSE,'101',83),
(330,TRUE,'137',83),
(331,FALSE,'145',83),
(332,FALSE,'152',83),
(333,TRUE,'La Constitución',84),
(334,FALSE,'La Ley reguladora de las bases del régimen local',84),
(335,FALSE,'El Texto refundido de disposiciones vigentes en materia de régimen local',84),
(336,FALSE,'El Reglamento de servicios de las corporaciones locales',84),
(337,FALSE,'Pactada, extensa, rígida y completa',85),
(338,FALSE,'Pactada, escueta, rígida e incompleta',85),
(339,TRUE,'Popular, extensa, rígida e incompleta',85),
(340,FALSE,'Popular, extensa, reducida e incompleta',85),
(341,FALSE,'Municipios',86),
(342,FALSE,'Provincias',86),
(343,TRUE,'Islas',86),
(344,FALSE,'Comunidades Autónomas',86),
(345,FALSE,'a) Democráticos',87),
(346,TRUE,'b) Libres',87),
(347,FALSE,'c) Manifestación de la voluntad popular',87),
(348,FALSE,'d) A y B son correctas',87),
(349,FALSE,'Será pública y mediante voto secreto',88),
(350,TRUE,'Será pública y mediante llamamiento nominal',88),
(351,FALSE,'Será secreta y mediante voto también secreto',88),
(352,FALSE,'Será secreta y mediante voto nominal',88),
(353,FALSE,'Deberán contener la delimitación del territorio de las Provincias que la componen',89),
(354,FALSE,'Serán la norma fundamental de cada Comunidad Autónoma',89),
(355,TRUE,'Serán la norma institucional básica de cada Comunidad Autónoma',89),
(356,FALSE,'Sólo podrán ser reformados mediante la aprobación por las Cortes Generales de una Ley ordinaria',89),
(357,FALSE,'Sí, una reforma en el Título II de La Corona',90),
(358,FALSE,'Si, ha sufrido una única reforma en su estructura en el año 1992',90),
(359,FALSE,'No, no ha habido quórum para proceder a la reforma del Título II de La Corona, en concreto el artículo 57',90),
(360,TRUE,'Si, ha sufrido dos reformas, la primera en el año 1992 y la segunda en el año 2011',90),
(361,FALSE,'El libre establecimiento de bienes en todo el territorio español',91),
(362,FALSE,'Las diferencias entre los Estatutos de las distintas Comunidades Autónomas',91),
(363,FALSE,'El establecimiento de un equilibrio económico sostenible',91),
(364,TRUE,'La realización efectiva del principio de solidaridad',91),
(365,FALSE,'La Monarquía constitucional',92),
(366,FALSE,'El Estado social y democrático de Derecho',92),
(367,TRUE,'La Monarquía parlamentaria',92),
(368,FALSE,'La Monarquía absoluta',92),
(369,TRUE,'La Constitución se fundamenta en la indisoluble unidad de la Nación española, patria común e indivisible de todos los españoles, y reconoce y garantiza el derecho a la autonomía de las nacionalidades y regiones que la integran y la solidaridad entre todas ellas',93),
(370,FALSE,'El Español es la lengua oficial del Estado',93),
(371,FALSE,'La Capital del Estado es la villa de Madrid',93),
(372,FALSE,'España se constituye en un Estado Social y Democrático de derecho, que propugna como valores superiores de su Ordenamiento Jurídico la libertad, la justicia, la igualdad y el pluralismo político',93),
(373,FALSE,'Entidad Local con personalidad jurídica propia, determinada por la agrupación de municipios y división territorial para el cumplimiento de sus fines. Cualquier alteración de los límites provinciales habrá de ser aprobada mediante Ley',94),
(374,TRUE,'Entidad Local con personalidad jurídica propia, determinada por la agrupación de municipios y división territorial para el cumplimiento de las actividades del Estado. Cualquier alteración de los límites provinciales habrá de ser aprobada mediante Ley orgánica',94),
(375,FALSE,'Entidad Local con personalidad jurídica propia, determinada por la agrupación de municipios y división territorial para el cumplimiento de las actividades del Estado y de las CCAA. Cualquier alteración de los límites provinciales habrá de ser aprobada mediante Ley orgánica',94),
(376,FALSE,'Ninguna de las respuestas anteriores es correcta',94),
(377,FALSE,'Impuestos propios',95),
(378,FALSE,'Participación en los tributos de las Provincias',95),
(379,FALSE,'Participación en los tributos del Estado y de las Provincias',95),
(380,TRUE,'Tributos propios y de participación en los del Estado y de las Comunidades Autónomas',95),
(381,FALSE,'a) Cabildos',96),
(382,FALSE,'b) Consejos',96),
(383,FALSE,'c)  A y B son incorrectas',96),
(384,TRUE,' d) A y B son correctas',96),
(385,FALSE,'Se regulan por Ley Ordinaria, conforme al mandato constitucional',97),
(386,FALSE,'Se regulan por Real Decreto Ley conforme al mandato constitucional',97),
(387,TRUE,'Se regulan por Ley Orgánica, conforme al mandato constitucional',97),
(388,FALSE,'Se regulan en la propia Constitución, en el Título II',97),
(389,FALSE,'Sanidad e Higiene',98),
(390,FALSE,'Ordenación del territorio, urbanismo y vivienda',98),
(391,FALSE,'Los montes y aprovechamientos forestales',98),
(392,TRUE,'Legislación sobre propiedad intelectual e industrial',98),
(393,TRUE,'Ley orgánica',99),
(394,FALSE,'Ley',99),
(395,FALSE,'Real Decreto',99),
(396,FALSE,'Reglamento',99),
(397,TRUE,'La irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales',100),
(398,FALSE,'Que los poderes públicos actúen arbitrariamente',100),
(399,FALSE,'Las respuestas anteriores son correctas',100),
(400,FALSE,'Ninguna es correcta',100);
